prepare:
	@rm -rf ./src
	@mkdir src
	@touch ./src/CMakeLists.txt
	@echo "add_subdirectory(lib_iec60730_cmake)" >> ./src/CMakeLists.txt
vmc_support:
	@echo "add_subdirectory(lib_iec60730_vmc_support_cmake)" >> ./src/CMakeLists.txt