name: Coding Convention
on: 
  push:
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
jobs:
  job1:
    name: Check coding convention
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        ref: create-unit-test-functions-in-lib-iec60730
    - name: Check working directory
      run: |
        pwd 
        ls -la
    - name: Set up environment
      run: |
        pip install pre-commit
        sudo apt install uncrustify clang-tidy cppcheck
    - name: Run test
      run: |
        pre-commit run --files 
          
    
  
  
          
