name: Coding Convention
on: 
  push:
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
jobs:
  job1:
    name: Check coding convention
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Check working directory
      run: |
        pwd 
        ls -la
    - name: Set up environment
      run: |
        pip install pre-commit
        sudo apt install uncrustify clang-tidy cppcheck
    - name: Run test
      run: |
        git diff --name-only main $BRANCH_NAME | pre-commit run --files > CodingConventionTool.log
    - name: Upload Result
      uses: actions/upload-artifact@v4.3.4
      with:
        name: CodingConventionTool.log
        path: .
        warn: Output a warning but do not fail the action
        retention-days: 90
          
    
  
  
          
