name: Hello World Workflow

on:
  push:                     
    branches:
      - main
  pull_request:            
  workflow_dispatch:       

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"

