name: Generate Firmware
on: 
  push:

env:
  TOOL_DIRS: ~/SimplicityStudio_v5/developer/toolchains/gnu_arm/12.2.rel1_2023.7/bin
  SDK_PATH: ~/SimplicityStudio/SDKs/gecko_sdk
  TOOL_CHAINS: GCC
  START_ADDR_FLASH: 0x8000000
jobs:
  job1:
    name: Generate Firmware
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    env: 
      HOST_IP: 192.168.1.69
      COMPILER: GCC
      PLATFORM: MG12
      APP_TYPE: SecureApp
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Generate Firmware
      run: |
        pwd
        ls -la
        chmod -R 777 . 
        cd Test/
        ls -la
        ./generate_fw.sh $COMMAND $COMPONENT $PLATFORM $COMPILER $SECURITY

    - name: Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554
      uses: TheDoctor0/zip-release@0.7.6
      with:
        # Filename for archive
        filename: firmware.7z
        # Base path for archive files
        path: artifact
        # Working directory before zipping
        directory: .
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: firmware.7z
        path: firmware.7z
        warn: Output a warning but do not fail the action
        retention-days: 90

    
  
  
          
