name: Automation Trigger
on: 
  pull_request:
      types: [opened, edited, review_requested, synchronize, review_request_removed, reopened]
      branches:
        - main
  workflow_dispatch:

jobs:
  job1:
    name: GCC-MG12 regression test
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Check ubuntu version
      run: 
        uname -r
        ifconfig
  

    
  
  
          
