name: Generate Firmware
on: 
  pull_request:
      types: [opened, edited, review_requested, synchronize, review_request_removed, reopened]
      branches:
        - main
        - iec_efr32

env:
  SECURITY: APP_SECURE=false
  COMMAND: all
  COMPONENT: all
jobs:
  job1:
    name: GCC-MG12 regression test
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    env: 
      HOST_IP: 192.168.1.69
      COMPILER: GCC
      PLATFORM: MG12
      TOOL_DIRS: docker/gcc-arm-none-eabi-10.3-2021.10/bin
      APP_TYPE: SecureApp
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
          
    - name: Prepare environment
      run: |
        cd docker
        wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-aarch64-linux.tar.bz2?rev=b748c39178c043b4915b04645d7774d8&hash=9E173D105DC6E0D452EB3A813BF28AAB
        tar xjf gcc-arm-none-eabi-10.3-2021.10-aarch64-linux.tar.bz2
        git clone ssh://git@stash.silabs.com/toolchain_external/iar_bxarm_9204_linux_jenkins.git
        ls -la
        
    - name: Generate Firmware
      run: |
        pwd &&
        ls -la
        chmod -R 777 . 
        cd Test/ &&
        ls -la &&
        ./generate_fw.sh $COMMAND $COMPONENT $PLATFORM $COMPILER $SECURITY

    - name: Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554
      uses: TheDoctor0/zip-release@0.7.6
      with:
        # Filename for archive
        filename: firmware.7z
        # Base path for archive files
        path: artifact
        # Working directory before zipping
        directory: .
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: firmware
        path: .
        warn: Output a warning but do not fail the action
        retention-days: 90

    
  
  
          
