name: Generate Firmware
on: 
  push:

env:
  TOOL_DIRS: /home/sqa/SimplicityStudio-5/SimplicityStudio_v5/developer/toolchains/gnu_arm/10.3_2021.10/bin
  SDK_PATH: /home/sqa/SimplicityStudio/SDKs/gecko_sdk
  TOOL_CHAINS: GCC
  START_ADDR_FLASH: 0x8000000
jobs:
  job1:
    name: Generate Firmware
    runs-on: [self-hosted, ds-sqa-hn-iec]
    permissions:
      contents: read
      pull-requests: write
    env: 
      HOST_IP: 192.168.1.69
      COMPILER: GCC
      PLATFORM: MG12
      APP_TYPE: SecureApp
      SECURITY: APP_SECURE=false
      COMMAND: all
      COMPONENT: all
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        ref: create-unit-test-functions-in-lib-iec60730
    - name: Prepare environment
      run: |
        wget https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
        export SDK_PATH=~/SimplicityStudio/SDKs/gecko_sdk
        export TOOL_DIRS=~/Downloads/SimplicityStudio_v5/developer/toolchains/gnu_arm/12.2.rel1_2023.7/bin
        export TOOL_CHAINS=GCC
        export START_ADDR_FLASH=0x8000000
        cd make
        make clean_all
        make build COMPONENT=cpu_registers DERIVATIVE=efr32mg21a020f1024im32 NON_SECURE_EN=false APP_SECURE=true
        ls -la
        cd ..
        ls -la
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: firmware
        path: artifact
        warn: Output a warning but do not fail the action
        retention-days: 90

    
  
  
          
