name: Manual Regression Test
on: 
  workflow_dispatch:
    inputs:
      branch: 
        description: 'Branch to test'
        type: string
        default: 'iec_efr32'

      test_mg12:
        description: 'Run test with MG12?'
        type: boolean
        default: 'true'
      test_mg24:
        description: 'Run test with MG24?'
        type: boolean
        default: 'true'
      
      mg12_serialnum:
        description: 'Serial number of target board to test for GCC MG12'
        type: string
        default: '440189400'
      mg12_hostip:
        type: string
        default: '192.168.1.69'
      mg24_serialnum:
        description: 'Serial number of target board to test for GCC MG12'
        type: string
        default: '440133193'
      mg24_hostip:
        type: string
        default: '192.168.1.100'

      security:
        description: 'NON_SECURE_EN= true "CRC_32=1%20NON_SECURE_EN=false%20N_CRC_DEBUG=1%20APP_SECURE=false"'
        type: string
        default: 'APP_SECURE=false'
      command:
        type: choice
        options:
        - all
        - gen-only
        - run-only
      component:
        type: choice
        options:
        - all
        - cpu_registers
        - programme_counter
        - invariable_memory
        - system_clock
        - variable_memory
        - watchdog
        - bist
        - post
        - irq
        - integrated
jobs:
  job1:
    if: github.event.inputs.test_mg12 == 'true'
    name: GCC-MG12 regression test
    runs-on: [self-hosted, sqa-ds-hn-006]
    permissions:
      contents: read
      pull-requests: write
    env: 
      COMPILER: GCC
      PLATFORM: MG12
      TOOL_DIRS: /home/sqa/SimplicityStudio-5/SimplicityStudio_v5/developer/toolchains/gnu_arm/10.3_2021.10/bin
      APP_TYPE: SecureApp 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        ref: "${{ github.event.inputs.branch }}"
    - name: Check working directory
      run: 
        pwd &&
        ls -la
    - name: Prepare Test directory
      run: 
        chmod -R 777 ./Test 
    - name: Testing
      run:
        export HOST_IP=${{ github.event.inputs.mg12_hostip }} &&
        export SERIAL_NUM=${{ github.event.inputs.mg12_serialnum }} &&
        export SECURITY=${{ github.event.inputs.security }} &&
        export COMMAND=${{ github.event.inputs.command }} &&
        export COMPONENT=${{ github.event.inputs.component }} &&
        cd Test/ &&
        ls -la &&
        echo "./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY" &&
        ./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY

    - name: Generate test report
      run: 
        cd Test/ &&
        ls -la &&
        python test_script/get_report.py 

    - name: Upload result
      uses: actions/upload-artifact@v4.3.4
      with:
        name: gcc_mg12_result
        path: 
          result/
        warn: Output a warning but do not fail the action
        retention-days: 90
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: gcc_mg12_artifact
        path: 
          artifact/
        warn: Output a warning but do not fail the action
        retention-days: 90
    - name: Upload log
      uses: actions/upload-artifact@v4.3.4
      with:
        name: gcc_mg12_log
        path: 
          log/
        warn: Output a warning but do not fail the action
        retention-days: 90
  
  job2:
    if: (always()) && github.event.inputs.test_mg24 == 'true'
    needs: [job1]
    name: GCC-MG24 regression test
    runs-on: [self-hosted, sqa-ds-hn-006]
    permissions:
      contents: read
      pull-requests: write
    env:
      COMPILER: GCC
      PLATFORM: MG24
      TOOL_DIRS: /home/sqa/SimplicityStudio-5/SimplicityStudio_v5/developer/toolchains/gnu_arm/10.3_2021.10/bin
      APP_TYPE: SecureApp 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        ref: "${{ github.event.inputs.branch }}"
    - name: Check working directory
      run: 
        pwd &&
        ls -la
    - name: Prepare Test directory
      run: 
        chmod -R 777 ./Test 
        
    - name: Testing
      run:
        export HOST_IP=${{ github.event.inputs.mg24_hostip }} &&
        export SERIAL_NUM=${{ github.event.inputs.mg24_serialnum }} &&
        export SECURITY=${{ github.event.inputs.security }} &&
        export COMMAND=${{ github.event.inputs.command }} &&
        export COMPONENT=${{ github.event.inputs.component }} &&
        cd Test/ &&
        ls -la &&
        echo "./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY" &&
        ./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY

    - name: Generate test report
      run: 
        cd Test/ &&
        ls -la &&
        python test_script/get_report.py 

    - name: Upload result
      uses: actions/upload-artifact@v4.3.4
      with:
        name: gcc_mg24_result
        path: 
          result/
        warn: Output a warning but do not fail the action
        retention-days: 90
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: gcc_mg24_artifact
        path: 
          artifact/
        warn: Output a warning but do not fail the action
        retention-days: 90
    - name: Upload log
      uses: actions/upload-artifact@v4.3.4
      with:
        name: gcc_mg24_log
        path: 
          log/
        warn: Output a warning but do not fail the action
        retention-days: 90
  
  job3:
    if: (always()) && github.event.inputs.test_mg12 == 'true'
    needs: [job1, job2]
    name: IAR-MG12 regression test
    runs-on: [self-hosted, sqa-ds-hn-006]
    permissions:
      contents: read
      pull-requests: write
    env: 
      COMPILER: IAR
      PLATFORM: MG12
      TOOL_DIRS: /home/sqa/EmbeddedWorkbench8.4/arm/bin
      APP_TYPE: SecureApp 
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        ref: "${{ github.event.inputs.branch }}"
    - name: Check working directory
      run: 
        pwd &&
        ls -la
    - name: Prepare Test directory
      run: 
        chmod -R 777 ./Test 

    - name: Testing
      run:
        export HOST_IP=${{ github.event.inputs.mg12_hostip }} &&
        export SERIAL_NUM=${{ github.event.inputs.mg12_serialnum }} &&
        export SECURITY=${{ github.event.inputs.security }} &&
        export COMMAND=${{ github.event.inputs.command }} &&
        export COMPONENT=${{ github.event.inputs.component }} &&
        cd Test &&
        ls -la &&
        echo "./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY" &&
        ./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY

    - name: Generate test report
      run:  
        cd Test/ &&
        ls -la &&
        python test_script/get_report.py 

    - name: Upload result
      uses: actions/upload-artifact@v4.3.4
      with:
        name: iar_mg12_result
        path: 
          result/
        warn: Output a warning but do not fail the action
        retention-days: 90
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: iar_mg12_artifact
        path: 
          artifact/
        warn: Output a warning but do not fail the action
        retention-days: 90
    - name: Upload log
      uses: actions/upload-artifact@v4.3.4
      with:
        name: iar_mg12_log
        path: 
          log/
        warn: Output a warning but do not fail the action
        retention-days: 90
  
  job4:
    if: (always()) && github.event.inputs.test_mg24 == 'true'
    needs: [job1, job2, job3]    
    name: IAR-MG24 regression test
    runs-on: [self-hosted, sqa-ds-hn-006]
    permissions:
      contents: read
      pull-requests: write
    env: 
      COMPILER: IAR
      PLATFORM: MG24
      TOOL_DIRS: /home/sqa/EmbeddedWorkbench8.4/arm/bin
      APP_TYPE: SecureApp 
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        ref: "${{ github.event.inputs.branch }}"
  
    - name: Check working directory
      run: 
        pwd &&
        ls -la
    - name: Prepare Test directory
      run: 
        chmod -R 777 ./Test 

    - name: Testing
      run:
        export HOST_IP=${{ github.event.inputs.mg24_hostip }} &&
        export SERIAL_NUM=${{ github.event.inputs.mg24_serialnum }} &&
        export SECURITY=${{ github.event.inputs.security }} &&
        export COMMAND=${{ github.event.inputs.command }} &&
        export COMPONENT=${{ github.event.inputs.component }} &&
        cd Test &&
        ls -la &&
        echo "./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY" &&
        ./execute_test.sh $COMMAND $COMPONENT $SERIAL_NUM $PLATFORM $COMPILER $SECURITY

    - name: Generate test report
      run:  
        cd Test/ &&
        ls -la &&
        python test_script/get_report.py 

    - name: Upload result
      uses: actions/upload-artifact@v4.3.4
      with:
        name: iar_mg24_result
        path: 
          result/
        warn: Output a warning but do not fail the action
        retention-days: 90
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: iar_mg24_artifact
        path: 
          artifact/
        warn: Output a warning but do not fail the action
        retention-days: 90
    - name: Upload log
      uses: actions/upload-artifact@v4.3.4
      with:
        name: iar_mg24_log
        path: 
          log/
        warn: Output a warning but do not fail the action
        retention-days: 90
    
  
  
          
