name: Unit Tests Auto Trigger
on: 
  push:

jobs:
  job1:
    name: Unit test
    runs-on: [self-hosted, ds-sqa-hn-003]
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Unit Testing
      run: |
        make prepare
        cd build
        cmake --toolchain ../cmake/toolchain.cmake .. -DENABLE_UNIT_TESTING=ON -DBOARD_NAME=brd4187c
        make unit_tests -j4
        
